# Generated by Django 5.0.1 on 2024-01-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_seller_product_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='customer',
            new_name='seller',
        ),
    ]
